# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи перестановки та символ Леві-Чивіти.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

while type:
    try:
        dim=int(input('Введіть розмірність квадратної матриці (1 число): '))
        if dim<0:
            print('Неправильний формат. Введіть 1 додатнє число!')
            continue
        else:
            break
        break
    except ValueError:
        print("Неправильний формат. Введіть 1 ціле число!")
m=random_matrix(dim)
print(m)
def permutat(dim):
    """The function creat list of permutations."""
    p=[]
    for i in range(1,dim+1):
        p.append(i)
    t = list(itertools.permutations(p, dim))
    return t
t=permutat(dim)
def multip(t):
    """The function creat list of multiplication's results ."""
    k=0
    new_l=[]
    for i in t:
        for j in range(len(i)):
            for n in range(j,len(i)):
                if i[j]>i[n]:
                    k+=1
        a=(-1)**k
        for j in range(len(i)):
            g2=i[j]
            a*=m[j][g2-1]
        new_l.append(a)
        k=0
    return new_l

def sum(new_l):
    """The function add multiplication's results to each other (add elements from list) and return the result (determinant)  ."""
    s=0
    for i in new_l:
        s+=i
    return s
print(sum(multip(t)))





[[2 1 9]
 [9 6 9]
 [1 3 9]]
171
